### ISSUE TITLE
El Capitan install issue

### ISSUE THREAD

**Issue by oneSIX** [jonathanzong/3d-print-letterpress#2]
Here is the output when I run the install.  Let me know if you have any other info you may need.
-Kent

Last login: Wed Sep 30 14:34:28 on ttys001
Kents-MacBook-Air:~ KentBookAir$ npm install git+ssh://git@github.com:jonathanzong/3d-print-letterpress.git -g
|

> contextify@0.1.14 install /usr/local/lib/node_modules/3d-print-letterpress/node_modules/node-raphael/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note:
      candidate function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
/Users/KentBookAir/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note:
      candidate function not viable: 2nd argument ('const char _') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/KentBookAir/.node-gyp/4.1.1/include/node/node_buffer.h:28:40: note:
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate, size_t length);
                                       ^
/Users/KentBookAir/.node-gyp/4.1.1/include/node/node_buffer.h:36:40: note:
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:676:12: error: no viable conversion from
      'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocalv8::Object' to 'const
      v8::Localv8::Object &' for 1st argument
class Local {
      ^
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object &&'
      for 1st argument
class Local {
      ^
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:214:13: note: candidate
      template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:326:13: note: candidate
      template ignored: could not match 'S _' against
      'v8::MaybeLocalv8::Object'
  V8_INLINE Local(S_ that)
            ^
In file included from ../src/contextify.cc:3:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    _(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
      specialization 'v8::Localv8::Primitive::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Boolean _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
      specialization 'v8::Localv8::Boolean::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Function _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
      specialization 'v8::Localv8::Function::Localv8::Value' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Object _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
      specialization 'v8::Localv8::Object::Localv8::Value' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).Asv8::Object());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Value _volatile' from incompatible type 'v8::Context *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:267:10: note: in instantiation of function template
      specialization 'v8::Localv8::Value::Localv8::Context' requested here
  return NanNew(val);
         ^
../src/contextify.cc:159:16: note: in instantiation of function template
      specialization '_NanEnsureLocalv8::Local<v8::Context >' requested here
        return NanEscapeScope(NanNew<Context>(
               ^
../node_modules/nan/nan.h:398:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Context _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:159:16: note: in instantiation of function template
      specialization 'v8::Localv8::Context::Localv8::Value' requested here
        return NanEscapeScope(NanNew<Context>(
               ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:7367:3: error: assigning to
      'v8::Integer _volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:211:13: note: in instantiation of function template
      specialization 'v8::ReturnValuev8::Integer::Setv8::Value' requested
      here
            NanReturnValue(NanNew<Integer>(None));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsu...

```
                                                        ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:7367:3: error: assigning to
      'v8::Boolean _volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:225:13: note: in instantiation of function template
      specialization 'v8::ReturnValuev8::Boolean::Setv8::Value' requested
      here
            NanReturnValue(NanNew<Boolean>(false));
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsu...

```
                                                        ^
```

In file included from ../src/contextify.cc:1:
In file included from /Users/KentBookAir/.node-gyp/4.1.1/include/node/node.h:42:
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:7367:3: error: assigning to
      'v8::Array _volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/KentBookAir/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:236:13: note: in instantiation of function template
      specialization 'v8::ReturnValuev8::Array::Setv8::Value' requested here
            NanReturnValue(blank);
            ^
../node_modules/nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsu...

```
                                                        ^
```

14 errors generated.
make: **\* [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/3d-print-letterpress/node_modules/node-raphael/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install" "git+ssh://git@github.com:jonathanzong/3d-print-letterpress.git" "-g"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/KentBookAir/npm-debug.log
Kents-MacBook-Air:~ KentBookAir$

**Comment by jonathanzong** [comment]
Hi Kent,

It seems like you're on Node v4.1.1 which is incompatible with the contextify dependency: https://github.com/brianmcd/contextify/issues/180

I suggest you try downgrading Node to v0.12 which is your best bet. If not, you could try modifying the package.json in 3d-print-letterpress to use the development branch in contextify.

**Comment by oneSIX** [comment]
Awesome!  I will take a look and get this running.  Thanks for the support!

update:  success!   Using [n](https://github.com/tj/n) to manage node version 3d-print-letterpress works with no errors.
On Wednesday, September 30, 2015, Jonathan Zong notifications@github.com
wrote:

> Hi Kent,
> 
> It seems like you're on Node v4.1.1 which is incompatible with the
> contextify dependency: brianmcd/contextify#180
> https://github.com/brianmcd/contextify/issues/180
> 
> I suggest you try downgrading Node to v0.12 or modify the package.json in
> 3d-print-letterpress to use the development branch in contextify.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonathanzong/3d-print-letterpress/issues/2#issuecomment-144538319
> .

## 

Kent Sinclair
Follow me on Instagram https://instagram.com/kentwatwit

**Comment by jonathanzong** [comment]
Glad it worked! :)
